language: node
sudo: required

services:
  - docker

before_install:
  - docker build -t "$DOCKER_USER"/fib-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true "$DOCKER_USER"/fib-client yarn test --coverage

after_success:
  - docker build -t "$DOCKER_USER"/multi-nginx ./nginx
  - docker build -t "$DOCKER_USER"/multi-fib-client ./client
  - docker build -t "$DOCKER_USER"/multi-fib-server ./server
  - docker build -t "$DOCKER_USER"/multi-fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/multi-nginx
  - docker push "$DOCKER_USER"/multi-fib-client
  - docker push "$DOCKER_USER"/multi-fib-server
  - docker push "$DOCKER_USER"/multi-fib-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-fib'
  env: 'MultiFib-env'
  bucket_name: 'elasticbeanstalk-us-west-1-475377943130'
  bucket_path: 'multi-fib'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
